import { FloatItem } from "@/interfaces";

export default [
  {
    alt: "Ovensandwich Hamburger Icon",
    src: "/assets/icons/hamburger-icon.png",
    height: 64,
    width: 64,
    top: 20,
    left: 16,
  },
  {
    alt: "Ovensandwich Baklava Icon",
    src: "/assets/icons/baklava-icon.png",
    height: 64,
    width: 64,
    top: 66,
    left: 60,
  },
  {
    alt: "Ovensandwich Bread Icon",
    src: "/assets/icons/bread-icon.png",
    height: 72,
    width: 72,
    top: 80,
    left: 46,
  },
  {
    alt: "Ovensandwich Tea Icon",
    src: "/assets/icons/tea-icon.png",
    height: 64,
    width: 64,
    top: 72,
    left: 24,
  },
  {
    alt: "Ovensandwich Hamburger Icon",
    src: "/assets/icons/hamburger-icon.png",
    height: 32,
    width: 32,
    top: 24,
    left: 48,
  },
  {
    alt: "Ovensandwich Salad Icon",
    src: "/assets/icons/salad-icon.png",
    height: 64,
    width: 64,
    top: 72,
    left: 72,
  },
  {
    alt: "Ovensandwich wrap Icon",
    src: "/assets/icons/wrap-icon.png",
    height: 80,
    width: 80,
    top: 24,
    left: 72,
  },
] as FloatItem[];
